version: '3'

services:
  fastapi:
    restart: always
    image: service-classification-model-training
    ports:
      - '8001:8000'
    env_file:
      - docker/.env
    volumes:
      - /workspace/data:/home/app/workdir/data

  sqlite-web:
    restart: always
    image: coleifer/sqlite-web
    ports:
      - '8081:8080'
    env_file:
      - docker/.env
    volumes:
      - /workspace/data/database:/data